# **************************************************************************** #
#                                                           LE - /             #
#                                                               /              #
#    Makefile                                         .::    .:/ .      .::    #
#                                                  +:+:+   +:    +:  +:+:+     #
#    By: fcordon <mhouppin@le-101.fr>               +:+   +:    +:    +:+      #
#                                                  #+#   #+    #+    #+#       #
#    Created: 2019/08/29 10:27:09 by fcordon      #+#   ##    ##    #+#        #
#    Updated: 2019/09/16 16:48:17 by fcordon     ###    #+. /#+    ###.fr      #
#                                                          /                   #
#                                                         /                    #
# **************************************************************************** #



all re clean fclean:
	make $@ -C create_object
	make $@ -C assemble_object
	make $@ -C router

.PHONY:	all re clean fclean
